services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - /Users/zh/Documents/workspace/zorg/NoteBook/:/app
    ports:
      - "6100:6100"
    command: npm ci && npm run build

  app-server:
    image: nginx:1.23.1
    volumes:
      - /Users/zh/Documents/workspace/zorg/NoteBook//.vitepress/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "6200:6200"
    depends_on:
      - app
