name: Deploy VitePress

on:
  push:
    branches:
      - master # Replace with your desired branch to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust as needed

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress site
        run: npx vitepress build && ls -a .vitepress

      - name: Upload to server via SCP
        run: |
          scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ./vitepress/dist ${{ secrets.SCP_USERNAME }}@${{ secrets.SCP_HOST }}:/var/www/html/z-doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vitepress/dist
