name: Deploy VitePress

on:
  push:
    branches:
      - master # Replace with your desired branch to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust as needed

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress site
        run: npx vitepress build && ls -a .vitepress

      - name: Upload to server via SCP
        uses: appleboy/scp-action@v0.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: './vitepress/dist'
          target: '/var/www/html/z-doc/dist' # Replace with the path on your server where you want to upload the files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vitepress/dist
